# Generated by Django 5.1.4 on 2025-09-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('premium', 'Premium'), ('sport', 'Sport'), ('hyper', 'Hyper')], default='premium', max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('acceleration', models.DecimalField(blank=True, decimal_places=2, help_text='Time in seconds', max_digits=4, null=True)),
                ('drive_type', models.CharField(choices=[('fwd', 'FWD'), ('rwd', 'RWD'), ('awd', 'AWD')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in km')),
                ('max_speed', models.PositiveIntegerField(help_text='Max speed in km/h')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per day', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('scale', models.CharField(blank=True, help_text='e.g. 1:8 scale', max_length=50)),
                ('rarity', models.CharField(blank=True, help_text='e.g. Limited edition of 199 pieces', max_length=100)),
                ('base_model', models.CharField(blank=True, help_text='Base dimensions and weight', max_length=255)),
                ('cover_model', models.CharField(blank=True, help_text='Cover dimensions and weight', max_length=255)),
                ('material_composition', models.TextField(blank=True, help_text='Detailed composition, e.g. 85% Polyurethane')),
                ('packing', models.TextField(blank=True, help_text='Packaging dimensions and weight')),
                ('thumbnail', models.ImageField(upload_to='cars/thumbnails/')),
                ('description', models.TextField(blank=True, help_text='Description of the car')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the social network', max_length=50)),
                ('url', models.URLField(help_text='Link to your profile or page')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rent.car')),
            ],
            options={
                'ordering': ['car'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='colors',
            field=models.ManyToManyField(blank=True, to='rent.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='materials',
            field=models.ManyToManyField(blank=True, to='rent.material'),
        ),
    ]
